language: php
php:
  - 5.6
  - 7.0

matrix:
  include:
  - php: 7.0
    env:
    - EXECUTE_DEPLOYMENT=true

before_install:
  - openssl aes-256-cbc -K $encrypted_9bbf475f87f0_key -iv $encrypted_9bbf475f87f0_iv -in .travis/secrets.tar.enc -out .travis/secrets.tar -d

before_script:
  - composer self-update
  - composer install --no-interaction

after_success:
  - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then composer install --no-dev ; fi
  - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./bin/deploy.sh ; fi